### ISSUE TITLE
Cannot interact with the dapp

### ISSUE THREAD

**Issue by clinton1719** [pmarella2/BroncoVotes#4]
I have done all the steps and deployed the contracts. I got the front page too, but nothing is happening when I input email id or random numbers. Any help would be appreciated!

P.S : Great work on this project!

**Comment by pmarella2** [comment]
Assuming you are still having this issue, please provide screenshots of the app once you set it up and run it. Also, another screenshot of the javascript errors that you get when attempting to interact with the app.

**Comment by clinton1719** [comment]
It keeps saying email address not valid. How does it register an email address?

I deployed it without errors, but unable to register an email address. I fixed some minor changes which i will upload soon! :)

**Comment by pmarella2** [comment]
The valid domains for e-mail addresses are found in Migrations/2_deploy_contracts.js
```
deployer.deploy(Registrar, ['gmail.com', 'yahoo.com', 'hotmail.com'].map(x => web3.utils.asciiToHex(x)), {
```
You can change the domains before deploying to accept whatever you want.

**Comment by pmarella2** [comment]
Closing this issue assuming you understood what needs to be fixed to run the web dApp.
